#include<bits/stdc++.h>
#define mod 1000000007
#define SIZE 1000007
#define ll long long
#define INF LLONG_MAX
#define fr(i,a,b) for(i=a;i<=b;i++)
using namespace std;

typedef pair<int,int> ii;
typedef vector<ii> vii;
typedef vector<int> vi;
typedef pair<string,int> si;

string str;
int mark[100],n;
vi::iterator itr;


int main() {
    freopen("inp.txt","r",stdin);
	freopen("out.txt","w",stdout);
    ios::sync_with_stdio(0);
    int tc,i,cunt;
    cin>>tc;
    for(int t=1;t<=tc;t++){
        cin>>str;
        vi ans;
        while(str.length()){
        n = str.length();
        //zero
        for(i=0;i<n;i++)
            if(str[i]=='Z')
                break;
        if(i<n){
            ans.push_back(0);
            for(i=0;i<n;i++)
                if(str[i]=='Z')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='R')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='O')
                    break;
            str.erase(i,1);
            continue;
        }
        //TWO
        for(i=0;i<n;i++)
            if(str[i]=='W')
                break;
        if(i<n){
            ans.push_back(2);
            for(i=0;i<n;i++)
                if(str[i]=='T')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='W')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='O')
                    break;
            str.erase(i,1);
            continue;
        }
        //SIX
        for(i=0;i<n;i++)
            if(str[i]=='X')
                break;
        if(i<n){
            ans.push_back(6);
            for(i=0;i<n;i++)
                if(str[i]=='S')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='I')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='X')
                    break;
            str.erase(i,1);
            continue;
        }
        //EIGHT
        for(i=0;i<n;i++)
            if(str[i]=='G')
                break;
        if(i<n){
            ans.push_back(8);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='I')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='G')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='H')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='T')
                    break;
            str.erase(i,1);
            continue;
        }
        //SEVEN
        for(i=0;i<n;i++)
            if(str[i]=='S')
                break;
        if(i<n){
            ans.push_back(7);
            for(i=0;i<n;i++)
                if(str[i]=='S')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='V')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='N')
                    break;
            str.erase(i,1);
            continue;
        }
        //THREE
        for(i=0;i<n;i++)
            if(str[i]=='T')
                break;
        if(i<n){
            ans.push_back(3);
            for(i=0;i<n;i++)
                if(str[i]=='T')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='H')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='R')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            continue;
        }
        //FIVE
        for(i=0;i<n;i++)
            if(str[i]=='V')
                break;
        if(i<n){
            ans.push_back(5);
            for(i=0;i<n;i++)
                if(str[i]=='F')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='I')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='V')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            continue;
        }
        //FOUR
        for(i=0;i<n;i++)
            if(str[i]=='F')
                break;
        if(i<n){
            ans.push_back(4);
            for(i=0;i<n;i++)
                if(str[i]=='F')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='O')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='U')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='R')
                    break;
            str.erase(i,1);
            continue;
        }
        //NINE
        for(i=0;i<n;i++)
            if(str[i]=='I')
                break;
        if(i<n){
            ans.push_back(9);
            for(i=0;i<n;i++)
                if(str[i]=='N')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='I')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='N')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            continue;
        }
        //ONE
        for(i=0;i<n;i++)
            if(str[i]=='O')
                break;
        if(i<n){
            ans.push_back(1);
            for(i=0;i<n;i++)
                if(str[i]=='O')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='N')
                    break;
            str.erase(i,1);
            for(i=0;i<n;i++)
                if(str[i]=='E')
                    break;
            str.erase(i,1);
            continue;
        }
        }

        sort(ans.begin(),ans.end());
		cout<<"Case #"<<t<<": ";
		for(itr=ans.begin();itr!=ans.end();itr++)
            cout<<(*itr);
		cout<<"\n";
	}
	return 0;
}
