from __future__ import division
from itertools import combinations
from sys import argv

import sys
sys.setrecursionlimit(110000)
qt = {}
i = 'i'
j = 'j'
k = 'k'
a = '1'

qt[(a,a)] = (a, 1)
qt[(a,i)] = (i, 1)
qt[(a,j)] = (j, 1)
qt[(a,k)] = (k, 1)

qt[(i,a)] = (i, 1)
qt[(i,i)] = (a, -1)
qt[(i,j)] = (k, 1)
qt[(i,k)] = (j, -1)

qt[(j,a)] = (j, 1)
qt[(j,i)] = (k, -1)
qt[(j,j)] = (a, -1)
qt[(j,k)] = (i, 1)

qt[(k,a)] = (k, 1)
qt[(k,i)] = (j, 1)
qt[(k,j)] = (i, -1)
qt[(k,k)] = (a, -1)

def reduce(s):
    """ reduces the given string using the qt """
    # print len(s)
    global qt
    # global red_sols
    # if s in red_sols: return red_sols[s]
    if not len(s):
        return ('', 1)
    if len(s) == 1:
        return (s[0], 1)
    if len(s) == 2:
        u, v = s[0], s[1]
        quv = qt[(u,v)]
        return quv[0], quv[1]

    base, sign = reduce(s[1:])
    # print base, sign
    # red_sols[s[1:]] = (base,sign)
    result = qt[(s[0], base)]
    newbase = result[0]
    newsign = result[1]*sign

    return newbase, newsign
    
def solve(s):
    # global red_sols
    global qt
    no = 'NO'
    yes = 'YES'
    sim_dic = {}
    i = 'i'
    j = 'j'
    k = 'k'
    a = '1'
    if len(s) < 3:
        return no
    if len(s) == 3:
        if s == 'ijk': return yes
        return no

    ct = (s[0], 1)
    all_i_indexes = []
    for i_index in xrange(1,len(s)-2):
        if ct[0] == i and ct[1] == 1:
            all_i_indexes.append(i_index-1)
        combine_c = qt[ct[0], s[i_index]]
        ct =(combine_c[0], ct[1]*combine_c[1])
    # print all_i_indexes

    et = (s[-1], 1)
    all_k_indexes = []
    for k_index in xrange(len(s)-2,1, -1):
        # print k_index, s[k_index], len(s)
        if et[0] == k and et[1] == 1:
            all_k_indexes.append(k_index+1)
        # combine_e = qt[et[0], s[k_index]]
        combine_e = qt[s[k_index],et[0]]
        # print s[k_index], k_index, et, combine_e[0], combine_e[1]*et[1]
        et =(combine_e[0], et[1]*combine_e[1])


    if not len(all_i_indexes): return no
    if not len(all_k_indexes): return no
    # print "now checking", len(all_i_indexes), len(all_k_indexes)
    for ai in all_i_indexes:
        for ak in filter(lambda aix: aix > ai, all_k_indexes):
            # print ai, ak
            dt =  reduce(s[ai+1:ak])
            # dt =  reduce(s[ai+1:ak])
            if dt[0] == j and dt[1] == 1:
                return yes
    return no

def main():
    filename = 'input.in'
    if len(argv) > 1:
        filename = argv[1]

    with open(filename) as f:
        T = int( f.readline() )
        case_count = 0
        for i in xrange(T):
            case_count += 1
            L, X = f.readline().rstrip('\n').split(' ')
            st = f.readline().rstrip('\n')
            st = st*int(X)
            # print len(st)
            red_value =  reduce(st)
            ans = ''
            if not (red_value[0] == '1' and red_value[1] == -1): ans = 'NO'
            else: ans = solve(st)
            print "Case #" + str(case_count) + ": " + str(ans)
    
main()
# print reduce('ijk')

# print reduce('iijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijjiijj')
# print reduce('jkjjjkiijkjiiiikjkkiijkjjkijjkiiijijjijkjkiikjiiiikjkiikjjijijkijikkjijkkjjkjkkijijiiikiijkjijkjjkkjikjkkkkjjiikjkkkjijkjkiijkkjkjijikjkiiijkkkjkkjkkkikijkijkijijijjkkjkkkijjjkkiikiiiijkkkjkiikijkjkikjjjjkijjkkikkijjjkiiikijkjkjiijijjiiikjjkiijkkjikkkkkjiiiiikjkkkjiiikjikiikikkjkjiikiiiikiikjkkijjikiiijijjjjjjiikkiijikjjijiikjkijjkikjkjjjkijjijkjjjjjikjikikjikkjkjijkkjikjjijikijiikkjiikkkjiiiiikkikijijijjjijkjikkkjijjjjjkjijkikjiikkikikiikjkikijkkikjkkjijijjjjjjkjiijjiikjkkijkkjijkiijjiijjjjkkkikjjkjikikjijikjkjjjikijkjkkjkkjjijijjkkjkjikijjkjkijjjikkkikkikikijjkijijjkkkijjkikkjiijijijjiijkijijijikiijjkiijiiikijkjkkjkjijjijijikijiijijjkikjijiikiijkjkiikijkjikiijikkjkkikkjkikjkkkjjkiijkkkkjkjjijiikiijjiiijkkiijkkjkkkkjjijikikkjjkjjjjikjkkkkkkikkjkiiikikkjjjkkjjkjiijkjkkiikjjkjkijjiiijjkjkkjikijijjjkjijkkjijikjijkkijkkjikkkikjiikkkikjkiijikikikjkkjkjiiijkkkkijjikkijikjkikjjijijkkkjkjikjkjjkkjjkkijjikkkjiiikikikkkkikkjkkikkkkjjjkkkkjkijkkkjjiikkkkikijjjjiikjijkjjikkkjiikjijkijiikkkjkijjijiikjkijkjjiiiiiijiijkjjjjjjijkikkjkkkjikjkjjijkiiijijjkikiiijkkiiikkkikkkiijikjijjikikjiikkjijikkjjkijijkijkjkjiijiijkjkiiikkkjjjkjjkjkjjkjjikjijkkkkikjkjjjiiiikikjijjkjjjjkkkikkjkkikjijjkjkiiijjijkkiiikkjkiijjkjikjkkikkkjiiijkjjkkjjkkjjkikiiiikiiikikkkiiiiiiijijjkjkjjkkikkjjjjjiikjijiijkkkijijijkkjkijijiiikjkjkkjkjkijijkjijiikjjiikikikijijikjkjkjkjkiiiijiiikiikkijjkkjkijkkkkikikiiijijikkjjjjjiikkjiikkiijkiikkikjijjkkjiijiikjjijkkikikijkiikkijkkjjikjiijijjkjkiikjkkikiikkjiijkkkkiikikjkikjikiijkjikkkkjkjiijikikjkjikiijkiikiiikikjijjkiikikkkjjjkiijikijjjjikijkikjjkjijijijijiijkjikkiiikjkjkikikjjjkkkkkiiijjiiijkkkijikjkjjjkkjikjkjkijkijjkiikjijijjiiijikkikkjkikijjkjiiikiiijijijjikiikkijkjkkijiiijjjkikijkkikjikjijjkkjjjjjikjjkiikjjkjjkjjjiikiiikijkkikkkjiijiiijjjjkjjkijjkjjjikjiijkikjkiiikkjikikikjkkjkiiijkjjjjikjkiiijkikjkikjijjkikijkjikjiijjjikjjkikjjkjjkkkjkiijikkjjkjkiijijiijkkkikkjikkkjikikjijkikkkiiiikkkjjkiiikjkkijikijijjkkkijjikijikikjjkkjkkkkkijjiiikkijjiiikkkjjkikikjkkjjjkijkkkkkjiikkkjkkikjjjikjkiikikkjiikijjijkkikkkiijjjkkiikkjjkkjjiikkjijijkjikikjkijkiijjikkjkikijikikjjjkjikiijiikjkkiijijijkkkijkijijikjkkjkjjikkjkjkiiijkkkijkikkkiijjjjiijiiiikjjkjjiijjjkkjijjkikikkjjijijkikjjiikikiijkkijkjjikiiijkijiikkikiiijiijjjjijiikiikiikikkikiiiiijkjkijkijkikjkikijijkikjkkkikjkikjkiiiikkkkjkjjjikjkjijjijikijikiikjjkikjiikijkjkjjjkjiiiikijjjjjiijikjkijkkiikjjkkkkjkikijijjkijkikkiikijjikikkkiijjijjkkkikijiijkkjjkiijjikkjikjikiiikkkkiijiikikkkjjjkkkkiiiijiijjkiikjkkkjkkkiijjiikkijiiijkjjikkkkijiikkjkkjjjjkkijjijkjkkjjjijikjkkjjiijkjijkkikijkkkkikkikjjjjiiikijiikkjkjkkjkijkiijikikjijiikkiijkjjikjkiiikkjjkjjjjiijkikkkiijkjkikkijjkkkijkiiiijiijjiikkkkjjjkjjjjkikijjikkkkkjjikiikikkkkikiijiijikiijijkjjjikiikkikkkiijiikiiiikikkikijijjjjjjjkjkjkijikkikjkiijiiiikjkijjjkijjijkijjjiijkijkkkjjijijijkikikiikkkkijikjiijkijjkkkijkjkikkjkijjkjjikjjjikjjkkjkjjjijkkkijijijkjjiiijkkjkjkjijikiijkjjjjkjikjijkjkkjjkiiikjjkijkjkkjkjjkkkikjiikkkjkikikkikkkjkkiiiiikiikkkikijikkikikjkijjkkiikikkjiiikjijjiijijjjjkjjijkjjjijkkiiikkjkjkijijiikjijjjjjkjikkkjkjjkkikkijjikjkjjjikjjkikijiikjkkjjkjkkjjkijjiijjkjjiiiiikjkkjiikijjjjiikkiiiiijikjikijkiikkkkjjjijkjjkkiijjkiijjikiikjkjijkjkiikikjikjjkkijijikkiikkjjjiiijkiiijijjjikkikkiiikjjjijjikikjkkkiijkikjijiiiiijkkjijjkjiikkkjjkkjjjjkjkjiijkjijkjjjiiiijkkkiiiijjjkiijjiiiikkkjikijikjiikijjkkikkikijkkjjkkkiijjkjkjijijiikjkkikkikjijikkjikjkikkkikijjiijkkjkjjjjikkjkikkjijkjkjkjjkijikkkjkjkkkikikikjjjikkjikiikiikikikkjikjjjiijjkjikjijiiikjjkjijjiikjiiiijkjiikikkiijijikjkikijkjijkjkkkijjjikkjkikjijkkjjiiikijkijjijijjkikkkiikijjkikjjkikjkijijkjiikkjkikjiikkkkkjiijkikjiiijijijikkjjiiiiikiikjkkkijkijkjjjiijijjiijkjkkkkiiikjkjjkkkjijjijjkjkkkikiikjkkijijjiikkijjjjiikkkijkjjjijkjiiiiiikkijkiiikikiikjkjikjikjijijkkkjkijikikjijikkjijjkjjjkkijjjkkkjkjkijijjkikjiijkkkkkkiikkiikjikikjjkijkkiiijkkjkjjjjjjkkkjjiijkkikiikijkikjjkkjikiijiiiiiijjiiiijiikkkkkkiijikjjikjkjiiiikijjkkjikjiikiikjkkkkkjikiiijjjjkikkjjkjjiijkkjjkijkkjijkkiijjjjjjkkkkijjijjjjkkjkkjjkikkkjkkikkiijjjjjikkkjkkkkijjkkijijkjkijikjjikijiijjjikkkikkkjkiikjjkkkjkikjkjiiijjikkkkkkkjijjkkjijjjjiikjjjiiikkikikkjjjkijijiikkjkijiijijkijijikkkiikjijkkiiiijjiiiikkkkikjikjikjjiijijkkjjikijjiikjkijkkkikkijkijkikikiiiijjiikkjijkkkiikiikikkjkkjkkkiijkijkkjkjkjikiijjijkkiiiijijkiiiijijkjkjjjjkjkijkikkijjjkikiijikjkjiikjkijkkijiijjkijjjjjikkjkjiiijijjjkijjikjkkkjkkjjkkkkiijkijkkkjjijkjikkjiijjjjjkjjkkjijijikkjkijiijiiijkkjkkjiiijijkjjkkkjikjjkiiikijjiijkjiijiijjjkkjjiijjkjkkjjjkjkkjjjkikjjkikjiijjkikiijjiijjkkjkikikiiiijjkjjijjkiiijiijkkijkkkkiijjijijijkjjkkikijkkijijiiiijkjkijkkkiijjkijjkjjijiijjkikkijjjjjijijiiijijikkjkiijjkkjkjkjkkkikjikiiikjjiikiijikkjikikikijjjikikjjkkiikikkjiiiijkjiiijjjkjijkkijikiikikiikikjiiijjikkiijjijkjijijkkjiijiikkiiikjikkkijkkkjjijkjkjjikijjjikjjikikkikikjjjkkjkiikkiiikkkkjiijkjkiikjjikjijkkkijkkkiiikikijkkjjiikjjkkjjiijijiijjjjkkiikiiiijkiiikkijijjijkjkjkikjkkkjjijiijkijjjkiikkjkikjkkjjkjkjjjikkjijiijkjjiikkjjjkjikjiijjjikkkjijjkkjijiikkkkkkjkjiiikikikkiikjjijkijiiikkjikkkjjjijjjiiijikkiiijkjijjjijjikjjkikijjkiijkiikjkkjkkikkkkijkjiikjkkkjjkjjkiikikikjkjiijkjjiiikkkkjkjijiiiikjiikjkjijkjkikiijkkjiikikikiijiiikkkkjijijkjijikjjijijiijijiijjkkkiikijikjikjkjkiiijikijjijkjkkikikkjkkkikjkkkkjiiiiikikjkiiijkkiiijkjijkijiikkikijkikikikkjjjkiiikikkjijkjkjjjikjkjkjiijjikjjijkikiijkkjijiijjjikiijjkjiikijikjjkijikkkkjjjikjkjiijjkijkkkiijikjkikjijikikiijiijikkjjiikkiiijkjjkjijjikjijijkjjkkkkkkikijijikjikkjkjijjjijiiijiijiijijiijkjijkjkkjkkikijikjijiikiiiikkikkijjiijjjkkikkkikkjjijikkkkikjjjijkijkjkjiiiiiikikkijijjkijijjkkijjikjkjjkkjkjiikijjjikiiijkjjkjkijijijjjikijiijiiiijiiiikijjkjjkjkjjjjjjiijkijjikkikjijikkkijkkijijjjkijikkjkiiiikkikjkijikkijiijkijjjijkjjijijjkjkkjjjjikjikjjiijijjjkkjjijkjkikjjjjiikjikkjjjjjkjikkkijjijjjiiiikijjijjijiiiiikjjkijkijjjjkjkjkjkkkikiikkkjjijikijkjijikijiijkjijjjkkjiijiiikkkjikjjjkkkikiikiijjikjkikjijijkjkijijijkjjkjijjikikkjjiijkjikjikikiiikijkkjijkjjikkikjikjkjiikjijkkijikjjiiiijiijkijkjjkjijjjjkikjjkkjikjiikkiikikkiikijkikkjiiijijikijjijkjijkjijkjjjkikjikijjkjjjikkkijkkikijkkkjjkiiijikkjijjkkkjkkjiijjkikjjjkjijjjjikijjjjjjijjiiijkiijijkjkjkijjkjiikkiikikkkkjikjiijkkkjkijiijkjikjjikkjkjjkjkkiikikikkjkikijjiijjkkjjiikjkikkkjjkkiijkikjijjkikkjkijijjiikjikjijkkijkjiiikjkjkjjjkjkjjiijikiijikkjiikjijikkkkjjkjijjjjjijjijiijikkkkjikjkiikijjjkjjjkjkjijkkijkkjijikjiijijikkkjkkijkkikjkkjkkkkiiiikiijjjkkjikkjikkkkikijkkiikiijkijjiijikijkkijkiiikjikjkiiiikkikkkikjijijkijjikkkjjkkikkikikiijkkiijiiikiiiiiikkikjijkijjikkkjjkjiijjjjjkijkkkkkijjkjjijikjijijjikkkiiikkikkijkjkjjjkkkjjijikjkkikiiiijkiiikjkjjjijjkijjkjkiikjjikiikkkiijikijijkijjikkkjjkjkjkikjkkkkijkkkikijikkkjjkjjiiikkiijjiijkkkjjjjijkikiiikjiiiijkjkkjkjikkijjkikiiiikijkjijikjikijkkiikjkijkiijkkkkjjkkiikkjjkijkjikijiijjiijikkiiiijkjkijjkijjiiiikkjkjijkijiikikiijjikjkjiikjijkijjkjjjjiijkkijkjjijkijkiikkiiikkkiiijkkjjiijkjkkiikjkikjikijjiijijkkijkijjjikjjkijkjjkikiikkijkiijjijikkijjjjijkkkkiikiijjjjijkkjjkijkjijjjikjjiijjiiikkjkjijkikiikjijiikjjijkjijkjkikkikjikjiikkjjkiiiijkiikkjjiiikkjkkjkikjjikkjijjjjkjkkjkjiiiiijikkjjiiikiijjjkjjjjjiijikikjjjijiikiijikkjjiikiikjjjjkikjikjkiikkikkikiiiikikkjkijkkikikkijiiijjijikikkkjkikjiijjjijkiiijjkkikkkkiiiijikiijkjikkkiijijkjkkkjkkijkkkkkjikjjijkkkikjkjjjiiiijjkijkkikijkiijikikjkijjkjkiijkkijkikikiikjikjiikkjjikiiiiiijjkjjjikjkkjkjiikkkijijkkjjijjijkjkjjikijjiikjiikjiikkkikijiijkkikkkkiiijjkikijkijijikiijkjjikjkjikjkikjkjijkiikkikiiijjiiiijijijkkikjiiijikikijkkjjkkjkikjjikjkkiijjkjkjjkiikijjkkjkiiijjkjjjjjijijkjjjiikjijjijijiikjkjijiiiiijjjijjjikjkikkkkkiikjkiikjjjjijijijiijjjiijkikkkkjikjkjjjkkkkiikjiikijkijiijkjjkiijijijkjjjiijijkkkijjkkkiiijjjkjjjijjjkkkkiiijikkkjjijijkjkkkijikijjjkkiiijjikjijikiijkkijikkjiikijjjkijkijkjkkjijkkiikiijikjiijiikjjkjkjjikikikkiiiikkkkkkikkjjjiijjjikjjjkjijiikkijkikkkiijjkjkjjiikjjkiijkijijjjkjkkiikikjkjjiiiiijkjjkkkkjikjkiiijjiijjiijijkikkijkiijiikkiikkjiikjikjikjkjkikkjjikkjjjikkjkjiijkikjkijjkiiiikkkijkiijjkjijkkjjikjkjijjijjjkikiikjiiikjkjikjjjikkkikkikiijkjkkjkijjiiiijjkjjkkkiijiiikkjkijijkjjijkjjikkikkjkkjkkkiiiijjjikijikkjkkiiijjjjkjkjkijijkiiijjijkjkjjjjikjjiiijkkjkikikjjikjkjkjjjiijiijjjkjiikijjjijijkkiiikikjijikjkkkkjjkkjjjjjkkikkkijkkjkjijjkkkikikikikkiijjkjikjjikkkjijjijikijkkikkjiijkjkkjkkkkjiiijjijiikjjkiijkiikiikkikiijkjjkkijiiijkikjijkjiikkjjiijjkikjkkijiikikjjkkijjjjjjkjiijkjjjkjkkjjiiikiijjjikkiiijjiikikiiijkikikjjikkkkijjjjkijijjkiikijjkiijiijiiijkiikjkjijkiijijjjkkkikjkijikjiijikjijkkijikiiikiijijjjijkkikikkjijkjjjijikikkkiikikjikikkkikjikikijkikikjkjkkijkjiiijkijjkkkkjijikjikijkjkjiiijkiiikjkijjkikiikkkkkijijikiikikkjijkikikkjkiiiijjikijkjkkjijjikkiikkkjjkjjjkjijikiijjkjkjkjjijjjikkiikijijikjikjikiijjiikjjkikiikkikikiiikkjiijijjkikkikjjjkjiikjijkijiikjijjkikjijkijjjjiijijijjikiiiijjjikjjijiikjijijkkjkikijijjjikjkkjjijkiiikiiiikikkijkkjkikijkikkjjjikijkiijjkkjiikjjikijikjkkijjiiijjkkikkjiiiikjjkjkjiijkijjkkijiiijjikikkjiiijkjiiijikjkjikkijjkijkiijjijjjkjjjjkijikikjjkikkjjkikiijjkkjjkjiikikkjkikjjkjjkkjiiiikijjkikijjjiijiijikkijjiikikjkkiikjkkkjjkjijjikjjjikjjkikjjjkjjiiijijkjkiiikikikjkkkikjkijjijkiijjjijkkkikiikkijjiijkiijjikkjkijijkjiijkijijkkjkjjikiiiiikjkikkkkiikkiijkjkikkjkjjjiiijkjjkijkjjjkkkikjkkikiikjijjkjjjiikikijjkijkiikjkjkkikjiijkkkkkiiijiijjkijijijjjiijijkjijiikjjkiijjkkjkijjkiikikjjjijiijkjiijkkiikiijjjiikikkjijjjikkjjiikjikjikjjkkjiiiiikkkijkjiikiikiijijiiiiikkjikkkikijkjjiijjjkjkkkkkkijijkjjjkkikjkijjjkjkkiijiiiiijiijkikjkkkkjjijkjkkjijkjijiikkjkjjikkkiikiiijjkkjikjkiijiiiikjkkjjkiijkkjijiiikijjjikkjiiiikjiikijikijkjikkjkjkiiijiijiijkijkjkjijjijkijkjjkkiiiiijjjikkiiikkijkikjijikikjkiijijkjikkkjijjjjjiiiiijjjkjjkiikjjkjjkjiijiiiikiijkiijiikijkkjikikjikjkkjiikikkkiikjjjkiiikkkiijjkkikjjkjkjjkkkkkjkijiikjijiijjjiiijjiiiikjiijjkijkijjkkikjijkjikjijijkkjiiijjkkjijiikkijkiijkikkkijjjkkjkiijkjjikkkiikjijkijikikijjjjjiikkijijjjijkijkkkkiikjkikjjjikikiijjkjjijjiijkkjjiijkkkkkkkiijjikjkjkjkjjjjjjjkjiikiikijijijkjiijkikjijjiijikjjijikkikkjjjikjikkkkjjkjikjijjiikkkjjkjjijkjkkjjjjjikkijiikiiiiii')
