#include <algorithm>
#include <iomanip>
#include <istream>
#include <map>
#include <ostream>
#include <set>
#include <sstream>
#include <utility>
#include <vector>
using namespace std;
// Solution template generated by caide


class Solution {
public:
    void solve(std::istream& in, std::ostream& out) {
        int T;
        in >> T;
        for (int test = 1; test <= T; ++test) {
            int n;
            in >> n;
            long long mx = 0;
            long long way1 = 0, way2 = 0;
            vector<long long> m(n);
            for (int i = 0; i < n; ++i) {
                in >> m[i];
                if (i > 0) {
                    mx = max(mx, m[i-1]-m[i]);
                    way1 += max(m[i-1]-m[i], 0LL);
                }
            }
            for (int i = 1; i < n; ++i) {
                way2 += min(m[i-1], mx);
            }
            out << "Case #" << test << ": " << way1 << " " << way2 << endl;
        }
    }
};

void solve(std::istream& in, std::ostream& out)
{
    out << std::setprecision(12);
    Solution solution;
    solution.solve(in, out);
}
#include <fstream>
#include <iostream>

int main() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);

    istream& in = cin;

    ostream& out = cout;
    solve(in, out);
    return 0;
}
