
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * Google code jam problem solver.
 * Template generated by <a href="https://github.com/Faylixe/jammy">Jammy</a> plugin.
 * 
 * @author
 */
public final class RankandFileSolver {

	/** Scanner instance that allows to parse problem input. **/
	private final Scanner scanner;

	/**
	 * Default constructor.
	 * 
	 * @param scanner Scanner instance that allows to parse problem input. 
	 */
	private RankandFileSolver(final Scanner scanner) {
		this.scanner = scanner;
	}

	/**
	 * Solve a problem instance using internal
	 * scanner to retrieve problem input.
	 */
	public void solve() {
		int n = scanner.nextInt();
		boolean[] m = new boolean[2501];
		for (int i = 1; i <= 2500; i++) {
			m[i] = false;
		}
		
		for (int i = 0; i < n * 2 - 1; i++) {
			for (int j = 0; j < n; j++) {
				int t = scanner.nextInt();	
				m[t] = !m[t];
			}
		}

		boolean first = true;
		for (int i = 1; i <= 2500; i++) {
			if (m[i]) {
				if (first) {
					System.out.print(i);
					first = false;
				} else {
					System.out.print(" " + i);
				}
			}
		}
		System.out.println();
	}

	/**
	 * Solver entry point.
	 * 
	 * @param args Command line parameters.
	 * @throws FileNotFoundException If input file could not be parsed.
	 */
	public static void main(final String [] args) throws FileNotFoundException {
		final File file = new File(args[0]);
		final Scanner scanner = new Scanner(file);
		final int n = scanner.nextInt();
		final RankandFileSolver solver = new RankandFileSolver(scanner);
		for (int i = 0; i < n; i++) {
			System.out.print("Case #" + (i + 1) + ": ");
			solver.solve();
		}
		scanner.close();
	}

}