#include<bits/stdc++.h>
using namespace std;
int a[30],ans[11];
char s[2005];
string digit[11];
int main()
{
    freopen("A-large.in","r",stdin);
    freopen("output.txt","w",stdout);
    int t,len,nub=1,i,j,k;
    scanf("%d",&t);
    digit[0]="ZERO";
    digit[1]="ONE";
    digit[2]="TWO";
    digit[3]="THREE";
    digit[4]="FOUR";
    digit[5]="FIVE";
    digit[6]="SIX";
    digit[7]="SEVEN";
    digit[8]="EIGHT";
    digit[9]="NINE";
    while(t--)
    {
        scanf("%s",s);
        printf("Case #%d: ",nub++);
        len=strlen(s);
        for(i=0;i<len;i++)
            a[s[i]-'A']++;
        for(i=0;i<10;i++)
        {
                while(a['Z'-'A']!=0)
                {
                    for(j=0;j<digit[0].size();j++)
                        a[digit[0][j]-'A']--;
                    ans[0]++;
                }
                while(a['W'-'A']!=0)
                {
                    for(j=0;j<digit[2].size();j++)
                        a[digit[2][j]-'A']--;
                    ans[2]++;
                }
                while(a['X'-'A']!=0)
                {
                    for(j=0;j<digit[6].size();j++)
                        a[digit[6][j]-'A']--;
                    ans[6]++;
                }
                while(a['G'-'A']!=0)
                {
                    for(j=0;j<digit[8].size();j++)
                        a[digit[8][j]-'A']--;
                    ans[8]++;
                }
                while(a['S'-'A']!=0)
                {
                    for(j=0;j<digit[7].size();j++)
                        a[digit[7][j]-'A']--;
                    ans[7]++;
                }
                while(a['V'-'A']!=0)
                {
                    for(j=0;j<digit[5].size();j++)
                        a[digit[5][j]-'A']--;
                    ans[5]++;
                }
                while(a['F'-'A']!=0)
                {
                    for(j=0;j<digit[4].size();j++)
                        a[digit[4][j]-'A']--;
                    ans[4]++;
                }
                while(a['O'-'A']!=0)
                {
                    for(j=0;j<digit[1].size();j++)
                        a[digit[1][j]-'A']--;
                    ans[1]++;
                }
                while(a['H'-'A']!=0)
                {
                    for(j=0;j<digit[3].size();j++)
                        a[digit[3][j]-'A']--;
                    ans[3]++;
                }
                while(a['I'-'A']!=0)
                {
                    for(j=0;j<digit[9].size();j++)
                        a[digit[9][j]-'A']--;
                    ans[9]++;
                }
            for(i=0;i<10;i++)
            {
                while(ans[i]!=0)
                {
                    printf("%d",i);
                    ans[i]--;
                }
            }
        }
        printf("\n");
    }
}
