from sys import stdin
def main():
	n=int(stdin.readline().strip())
	for i in range(n):
		s=stdin.readline().strip().lower()
		a=[]
		num=[]
		#print(s)
		for j in range(len(s)):
			a.append(s[j])
		while(len(a)>0):
			if(a.count('x')>0):
				#print(6)
				num.append(6)
				a.remove('s')
				a.remove('i')
				a.remove('x')
			elif(a.count('z')>0):
				#print(0)
				num.append(0)
				a.remove('z')
				a.remove('e')
				a.remove('r')
				a.remove('o')
			elif(a.count('w')>0):
				#print(2)
				num.append(2)
				a.remove('t')
				a.remove('w')
				a.remove('o')
			elif(a.count('u')>0):
				#print(4)
				num.append(4)
				a.remove('f')
				a.remove('o')
				a.remove('u')
				a.remove('r')
			elif(a.count('o')>0):
				#print(1)
				num.append(1)
				a.remove('o')
				a.remove('n')
				a.remove('e')
			elif(a.count('s')>0):
				#print(7)
				num.append(7)
				a.remove('s')
				a.remove('e')
				a.remove('v')
				a.remove('e')
				a.remove('n')
			elif(a.count('f')>0):
				#print(5)
				num.append(5)
				a.remove('f')
				a.remove('i')
				a.remove('v')
				a.remove('e')
			elif(a.count('n')>0):
				#print(9)
				num.append(9)
				a.remove('n')
				a.remove('i')
				a.remove('n')
				a.remove('e')
			elif(a.count('i')>0):
				#print(8)
				num.append(8)
				a.remove('e')
				a.remove('i')
				a.remove('g')
				a.remove('h')
				a.remove('t')
			elif(a.count('t')>0):
				#print(3)
				num.append(3)
				a.remove('t')
				a.remove('h')
				a.remove('r')
				a.remove('e')
				a.remove('e')
		num.sort()
		print('Case #'+str(i+1)+': ',end='')
		for j in range(len(num)):
			print(num[j],end='')
		print()
main()