#include<cstdio>
#include<set>
#include<algorithm>
#include<iostream>
using namespace std;
int main()
{
	int T,R,N,M,K,test,i,c1,flag;
	scanf("%d",&T);
	for(test=1;test<=T;test++)
	{
		scanf("%d%d%d%d",&R,&N,&M,&K);
		printf("Case #%d:\n",test);
		while(R--)
		{
			set<int >numbers;
			set<int >::iterator it;
			c1=0;
			int set[K];
			for(i=0;i<K;i++)
			{
				scanf("%d",&set[i]);
				if(set[i]==1)
					c1++;
			}
			if(c1==K)
				printf("222\n");
			else
			{
				flag=0;
				sort(set,set+K);
				for(i=K-1;i>=0;i--)
				{
					if(set[i]==125)
					{
						printf("555");
						flag=1;
						break;
					}
					if(set[i]==27)
					{
						printf("333");
						flag=1;
						break;
					}
					if(set[i]==64)
					{
						printf("444");
						flag=1;
						break;
					}
					if(set[i]==100)
					{
						printf("455");
						flag=1;
						break;
					}
					if(set[i]==75)
					{
						printf("355");
						flag=1;
						break;
					}
					if(set[i]==50)
					{
						printf("255");
						flag=1;
						break;
					}
					if(set[i]==32)
					{
						printf("244");
						flag=1;
						break;
					}
					if(set[i]==48)
					{
						printf("344");
						flag=1;
						break;
					}
					if(set[i]==80)
					{
						printf("445");
						flag=1;
						break;
					}
					if(set[i]==36)
					{
						printf("334");
						flag=1;
						break;
					}
					if(set[i]==45)
					{
						printf("335");
						flag=1;
						break;
					}
					if(set[i]==18)
					{
						printf("233");
						flag=1;
						break;
					}
					if(set[i]==16)
					{
						printf("224");
						flag=1;
						break;
					}
					
					if(set[i]==24)
					{
						printf("234");
						flag=1;
						break;
					}
					if(set[i]==30)
					{
						printf("235");
						flag=1;
						break;
					}
					if(set[i]==40)
					{
						printf("245");
						flag=1;
						break;
					}
					if(set[i]==60)
					{
						printf("345");
						flag=1;
						break;
					}
				}
				if(!flag)
				{
					for(i=K-1;i>=0;i--)
					{
						if(set[i]==6)
						{
							numbers.insert(2);
							numbers.insert(3);
						}
						if(set[i]==8)
						{
							numbers.insert(2);
							numbers.insert(4);
						}
						if(set[i]==10)
						{
							numbers.insert(2);
							numbers.insert(5);
						}
						if(set[i]==12)
						{
							numbers.insert(3);
							numbers.insert(4);
						}
						if(set[i]==15)
						{
							numbers.insert(5);
							numbers.insert(3);
						}
						if(set[i]==20)
						{
							numbers.insert(4);
							numbers.insert(5);
						}
						if(set[i]==2)
						{
							numbers.insert(2);
						}
						if(set[i]==3)
						{
							numbers.insert(3);
						}
						if(set[i]==4)
						{
							numbers.insert(4);
						}
						if(set[i]==5)
						{
							numbers.insert(5);
						}
						if(set[i]==9)
						{
							numbers.insert(3);
						}
						if(set[i]==16)
						{
							numbers.insert(4);
						}
						if(set[i]==25)
						{
							numbers.insert(5);
						}
					}
					if(numbers.size()==1)
					{
						cout<<*(numbers.begin());
						cout<<*(numbers.begin());
					}
					else if(numbers.size()==2)
					{
						for(it=numbers.begin();it!=numbers.end();++it)
						{
							if(*it==4)
							{
								flag=4;
							}
							else if(*it==3)
							{
								flag=3;
							}
							else if(*it==5)
							{
								flag=5;
							}
							else
							{
								flag=2;
							}
						}
						if(flag==4)
						{
							printf("2");
						}
						if(flag==3)
						{
							printf("3");
						}
						if(flag==5)
						{
							printf("5");
						}
					}
					for(it=numbers.begin();it!=numbers.end();++it)
					{
						cout<<*it;
					}
				}
				
				printf("\n");
			}
		}
	}
	return 0;
}