
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * Google code jam problem solver.
 * Template generated by <a href="https://github.com/Faylixe/jammy">Jammy</a> plugin.
 * 
 * @author
 */
public final class TheLastWordSolver {

	/** Scanner instance that allows to parse problem input. **/
	private final Scanner scanner;

	/**
	 * Default constructor.
	 * 
	 * @param scanner Scanner instance that allows to parse problem input. 
	 */
	private TheLastWordSolver(final Scanner scanner) {
		this.scanner = scanner;
	}

	/**
	 * Solve a problem instance using internal
	 * scanner to retrieve problem input.
	 */
	public void solve() {
		String s = scanner.next();
		String r = "";
		for (int i = 0; i <  s.length(); i++) {
			char c1 = s.charAt(i);
			if (r.length() == 0) {
				r = String.valueOf(c1);
			} else {
				char c2 = r.charAt(0);
				if (c1 >= c2) {
					r = c1 + r;
				} else {
					r = r + c1;
				}
			}
		}
		System.out.println(r);
	}

	/**
	 * Solver entry point.
	 * 
	 * @param args Command line parameters.
	 * @throws FileNotFoundException If input file could not be parsed.
	 */
	public static void main(final String [] args) throws FileNotFoundException {
		final File file = new File(args[0]);
		final Scanner scanner = new Scanner(file);
		final int n = scanner.nextInt();
		final TheLastWordSolver solver = new TheLastWordSolver(scanner);
		for (int i = 0; i < n; i++) {
			System.out.print("Case #" + (i + 1) + ": ");
			solver.solve();
		}
		scanner.close();
	}

}