# import section

def solve(inputFile, outputFile):
    # read case number

    # generated by script file
    Mapping = {}
    Mapping['a'] = 'y'
    Mapping['b'] = 'h'
    Mapping['c'] = 'e'
    Mapping['d'] = 's'
    Mapping['e'] = 'o'
    Mapping['f'] = 'c'
    Mapping['g'] = 'v'
    Mapping['h'] = 'x'
    Mapping['i'] = 'd'
    Mapping['j'] = 'u'
    Mapping['k'] = 'i'
    Mapping['l'] = 'g'
    Mapping['m'] = 'l'
    Mapping['n'] = 'b'
    Mapping['o'] = 'k'
    Mapping['p'] = 'r'
    Mapping['q'] = 'z'
    Mapping['r'] = 't'
    Mapping['s'] = 'n'
    Mapping['t'] = 'w'
    Mapping['u'] = 'j'
    Mapping['v'] = 'p'
    Mapping['w'] = 'f'
    Mapping['x'] = 'm'
    Mapping['y'] = 'a'
    Mapping['z'] = 'q'
    Mapping[' '] = ' '
    Mapping['\n'] = '\n'

    T = int(inputFile.readline())

    # iterate on all cases
    for t in xrange(T):
        # get input string
        inputLine = inputFile.readline()

        # initialize output string
        outputLine = 'Case #' + str(t + 1) + ': '

        # iterate on characters in line
        for c in inputLine:
            outputLine = outputLine + Mapping[c]

        # output case result
        outputFile.write(outputLine)