#include <bits/stdc++.h>
using namespace std;
int main()
{
	int t,u;
	cin>>t;
	u=t;
	while(t--)
	{
		int r,c,m,i,j,k;
		cin>>r>>c>>m;
		cout<<"Case #"<<u-t<<":"<<endl;
		char A[r][c];
		memset(A,'.',sizeof(A));
		if(r==1||c==1)
		{
			A[r-1][c-1]='c';
			for(i=0;i<r;i++)
			{
				for(j=0;j<c;j++)
				{
					if(m==0)
						break;
					A[i][j]='*';
					m--;
				}
				if(m==0)
					break;
			}
			for(i=0;i<r;i++)
			{
				for(j=0;j<c;j++)
				{
					cout<<A[i][j];
				}
				cout<<endl;
			}
		}
		else
		{
			if((r*c-m)>1&&(r*c-m)<4)
				cout<<"Impossible\n";
			else if((r*c-m)==4)
			{
				memset(A,'*',sizeof(A));
				A[r-1][c-1]='c';
				A[r-2][c-1]=A[r-1][c-2]=A[r-2][c-2]='.';
				for(i=0;i<r;i++)
				{
					for(j=0;j<c;j++)
					{
						cout<<A[i][j];
					}
					cout<<endl;
				}
			}
			else if((r*c-m)==1)
			{
				memset(A,'*',sizeof(A));
				A[r-1][c-1]='c';
				for(i=0;i<r;i++)
				{
					for(j=0;j<c;j++)
					{
						cout<<A[i][j];
					}
					cout<<endl;
				}
			}
			else
			{
				for(i=0;i<r-2;i++)
				{
					for(j=0;j<c-2;j++)
					{
						if(m==0)
							break;
						A[i][j]='*';
						m--;
					}
					if(m==0)
						break;
				}
				if(m&1)
				{
					if(r<3||c<3)
					{
						cout<<"Impossible\n";
						continue;
					}
					m++;
					A[r-3][c-3]='.';
					for(i=0;i<c-3;i++)
					{
						for(j=r-2;j<r;j++)
						{
							if(m==0)
								break;
							A[j][i]='*';
							m--;
						}
						if(m==0)
							break;
					}
					for(i=0;i<r-3;i++)
					{
						for(j=c-2;j<c;j++)
						{
							if(m==0)
								break;
							A[i][j]='*';
							m--;
						}
						if(m==0)
							break;
					}
					if(m>0)
					{
						cout<<"Impossible\n";
						continue;
					}
				}
				else
				{
					for(i=0;i<c-2;i++)
					{
						for(j=r-2;j<r;j++)
						{
							if(m==0)
								break;
							A[j][i]='*';
							m--;
						}
						if(m==0)
							break;
					}
					for(i=0;i<r-2;i++)
					{
						for(j=c-2;j<c;j++)
						{
							if(m==0)
								break;
							A[i][j]='*';
							m--;
						}
						if(m==0)
							break;
					}
				}
				A[r-1][c-1]='c';
				for(i=0;i<r;i++)
				{
					for(j=0;j<c;j++)
					{
						cout<<A[i][j];
					}
					cout<<endl;
				}
			}
		}
	}
	return 0;
}