#include <cstdio>
#include <iostream>
using namespace std;

int main()
{
    freopen("C-large.in","r",stdin);
    freopen("C-large.out","w",stdout);
    int q,t,i,j,r,c,m;
    scanf("%d",&t);
    for(q=0;q<t;q++)
    {
        scanf("%d %d %d",&r,&c,&m);
        printf("Case #%d:\n",q+1);
        if(m==0)
        {
            for(i=0;i<r;i++)
            {
                for(j=0;j<c;j++)
                {
                    if((i==0)&&(j==0))
                    {
                        printf("c");
                    }
                    else
                    {
                        printf(".");
                    }
                }
                printf("\n");
            }
        }
        else if(m==r*c-1)
        {
            for(i=0;i<r;i++)
            {
                for(j=0;j<c;j++)
                {
                    if((i==0)&&(j==0))
                    {
                        printf("c");
                    }
                    else
                    {
                        printf("*");
                    }
                }
                printf("\n");
            }
        }
        else if(r==1)
        {
            for(i=0;i<r;i++)
            {
                for(j=0;j<c;j++)
                {
                    if(j==0)
                    {
                        printf("c");
                    }
                    else if(j<c-m)
                    {
                        printf(".");
                    }
                    else
                    {
                        printf("*");
                    }
                }
                printf("\n");
            }
        }
        else if(c==1)
        {
            for(i=0;i<r;i++)
            {
                for(j=0;j<c;j++)
                {
                    if(i==0)
                    {
                        printf("c");
                    }
                    else if(i<r-m)
                    {
                        printf(".");
                    }
                    else
                    {
                        printf("*");
                    }
                }
                printf("\n");
            }
        }
        else if(r==2)
        {
            if((r*c-m==2)||((r*c-m)%2!=0))
            {
                printf("Impossible\n");
                continue;
            }
            for(i=0;i<r;i++)
            {
                for(j=0;j<c;j++)
                {
                    if((i==0)&&(j==0))
                    {
                        printf("c");
                    }
                    else if(j<c-m/2)
                    {
                        printf(".");
                    }
                    else
                    {
                        printf("*");
                    }
                }
                printf("\n");
            }
        }
        else if(c==2)
        {
            if((r*c-m==2)||((r*c-m)%2!=0))
            {
                printf("Impossible\n");
                continue;
            }
            for(i=0;i<r;i++)
            {
                for(j=0;j<c;j++)
                {
                    if((i==0)&&(j==0))
                    {
                        printf("c");
                    }
                    else if(i<r-m/2)
                    {
                        printf(".");
                    }
                    else
                    {
                        printf("*");
                    }
                }
                printf("\n");
            }
        }
        else
        {
            if((r*c-m==2)||(r*c-m==3)||(r*c-m==5)||(r*c-m==7))
            {
                printf("Impossible\n");
                continue;
            }
            if(r*c-m==4)
            {
                for(i=0;i<r;i++)
                {
                    for(j=0;j<c;j++)
                    {
                        if((i==0)&&(j==0))
                        {
                            printf("c");
                        }
                        else if((i<2)&&(j<2))
                        {
                            printf(".");
                        }
                        else
                        {
                            printf("*");
                        }
                    }
                    printf("\n");
                }
                continue;
            }
            if(r*c-m==6)
            {
                for(i=0;i<r;i++)
                {
                    for(j=0;j<c;j++)
                    {
                        if((i==0)&&(j==0))
                        {
                            printf("c");
                        }
                        else if((i<2)&&(j<3))
                        {
                            printf(".");
                        }
                        else
                        {
                            printf("*");
                        }
                    }
                    printf("\n");
                }
                continue;
            }
            if(r*c-m==9)
            {
                for(i=0;i<r;i++)
                {
                    for(j=0;j<c;j++)
                    {
                        if((i==0)&&(j==0))
                        {
                            printf("c");
                        }
                        else if((i<3)&&(j<3))
                        {
                            printf(".");
                        }
                        else
                        {
                            printf("*");
                        }
                    }
                    printf("\n");
                }
                continue;
            }
            if(r*c-m==8)
            {
                for(i=0;i<r;i++)
                {
                    for(j=0;j<c;j++)
                    {
                        if((i==0)&&(j==0))
                        {
                            printf("c");
                        }
                        else if((i<3)&&(j<3)&&((i<2)||(j<2)))
                        {
                            printf(".");
                        }
                        else
                        {
                            printf("*");
                        }
                    }
                    printf("\n");
                }
                continue;
            }
            if(r*c-m<=c*2)
            {
                if((r*c-m)%2==0)
                {
                    for(i=0;i<r;i++)
                    {
                        for(j=0;j<c;j++)
                        {
                            if((i==0)&&(j==0))
                            {
                                printf("c");
                            }
                            else if((i<2)&&(j<(r*c-m)/2))
                            {
                                printf(".");
                            }
                            else
                            {
                                printf("*");
                            }
                        }
                        printf("\n");
                    }
                }
                else
                {
                    for(i=0;i<r;i++)
                    {
                        for(j=0;j<c;j++)
                        {
                            if((i==0)&&(j==0))
                            {
                                printf("c");
                            }
                            else if(((i<2)&&(j<(r*c-m)/2-1))||((i==2)&&(j<3)))
                            {
                                printf(".");
                            }
                            else
                            {
                                printf("*");
                            }
                        }
                        printf("\n");
                    }
                }
            }
            else
            {
                if((r*c-m)%c!=1)
                {
                    for(i=0;i<r;i++)
                    {
                        for(j=0;j<c;j++)
                        {
                            if((i==0)&&(j==0))
                            {
                                printf("c");
                            }
                            else if((i<(r*c-m)/c)||((i==(r*c-m)/c)&&(j<(r*c-m)%c)))
                            {
                                printf(".");
                            }
                            else
                            {
                                printf("*");
                            }
                        }
                        printf("\n");
                    }
                }
                else if((r*c-m)/c!=2)
                {
                    for(i=0;i<r;i++)
                    {
                        for(j=0;j<c;j++)
                        {
                            if((i==0)&&(j==0))
                            {
                                printf("c");
                            }
                            else if((i<(r*c-m)/c-1)||((i==(r*c-m)/c-1)&&(j<c-1))||((i==(r*c-m)/c)&&(j<2)))
                            {
                                printf(".");
                            }
                            else
                            {
                                printf("*");
                            }
                        }
                        printf("\n");
                    }
                }
                else
                {
                    for(i=0;i<r;i++)
                    {
                        for(j=0;j<c;j++)
                        {
                            if((i==0)&&(j==0))
                            {
                                printf("c");
                            }
                            else if((i<(r*c-m)/c-2)||((i<(r*c-m)/c)&&(j<c-1))||((i==(r*c-m)/c)&&(j<3)))
                            {
                                printf(".");
                            }
                            else
                            {
                                printf("*");
                            }
                        }
                        printf("\n");
                    }
                }
            }
        }
    }
    return 0;
}
