#include<bits/stdc++.h>

using namespace std;
int main()
{
    long long int t,n,ans,x,y,squares,sidesq,sqr3,p,z,i;
    scanf("%lld",&t);
    p=0;
    while(t--)
    {
        p++;
        scanf("%lld %lld %lld",&x,&y,&n);
        for(i=1;i<=100000;i++);
        squares=x*y;
        sidesq=2*(x+y)-4;
        if(x==1||y==1)
        {
            if(squares%2!=0)
            {
                if(n>(squares/2)+1)
                {
                    n-=(squares/2)+1;
                    ans=2*n;
                }
                else
                {
                    ans=0;
                }
            }
            else
            {
                if(n>squares/2)
                {

                    ans=0;
                    n-=(squares/2)+1;
                    ans=1;
                }
                else
                {
                    ans=0;
                    n=0;
                }
                if(n>0)
                    ans+=2*n;
            }
        }
        else
        {
            if(squares%2==0)
            {
                if(n<=squares/2)
                {
                    ans=0;
                    n=0;
                }
                else
                {
                    ans=0;
                    n-=squares/2;
                    if(n>0)
                    {
                        ans+=2;
                        n--;
                    }
                    if(n>0)
                    {
                        ans+=2;
                        n--;
                    }
                    sqr3=(sidesq/2)-2;
                    if(n>0)
                    {
                        if(n>sqr3)
                        {
                            ans+=3*sqr3;
                            n-=sqr3;
                        }
                        else
                        {
                            ans+=n*3;
                            n=0;
                        }
                    }
                    if(n>0)
                    {
                        ans+=n*4;
                    }
                }
            }
            else
            {
                if(n<=(squares/2)+1)
                {
                    ans=0;
                    n=0;
                }
                else
                {
                    if(n!=(squares/2)+2)
                    {
                        ans=0;
                        n-=(squares/2);
                    }
                    else
                    {
                        ans=3;n=0;
                    }
                }
                if(n>0)
                {
                    ans+=2;
                    n--;
                }
                if(n>0)
                {
                    ans+=2;
                    n--;
                }
                if(n>0)
                {
                    ans+=2;
                    n--;
                }
                if(n>0)
                {
                    ans+=2;
                    n--;
                }
                sqr3=(sidesq/2)-4;
                if(n>0)
                {
                    if(n>sqr3)
                    {
                        ans+=3*sqr3;
                        n-=sqr3;
                    }
                    else
                    {
                        ans+=n*3;
                        n=0;
                    }
                }
                if(n>0)
                {
                    ans+=n*4;
                }
            }
        }
        printf("Case #%lld: %lld\n",p,ans);
    }
    return 0;
}
