#include <cstdio>
#include <cstring>
#include <cctype>

char mapa[500], s[102];

int main() {
		
	freopen("A-small-attempt0.in", "r", stdin); freopen("out.txt", "w", stdout);
	
	mapa['e'] = 'o';
	mapa['j'] = 'u';
	mapa['p'] = 'r';
	mapa[' '] = ' ';
	mapa['y'] = 'a';
	mapa['s'] = 'n';
	mapa['l'] = 'g';
	mapa['j'] = 'u';
	mapa['y'] = 'a';
	mapa['l'] = 'g';
	mapa['c'] = 'e';
	mapa[' '] = ' ';
	mapa['k'] = 'i';
	mapa['d'] = 's';
	mapa[' '] = ' ';
	mapa['k'] = 'i';
	mapa['x'] = 'm';
	mapa['v'] = 'p';
	mapa['e'] = 'o';
	mapa['d'] = 's';
	mapa['d'] = 's';
	mapa['k'] = 'i';
	mapa['n'] = 'b';
	mapa['m'] = 'l';
	mapa['c'] = 'e';
	mapa[' '] = ' ';
	mapa['r'] = 't';
	mapa['e'] = 'o';
	mapa[' '] = ' ';
	mapa['j'] = 'u';
	mapa['s'] = 'n';
	mapa['i'] = 'd';
	mapa['c'] = 'e';
	mapa['p'] = 'r';
	mapa['d'] = 's';
	mapa['r'] = 't';
	mapa['y'] = 'a';
	mapa['s'] = 'n';
	mapa['i'] = 'd';
	mapa['t'] = 'i';
	mapa['h'] = 'b';
	mapa['e'] = 'c';
	mapa['r'] = 'p';
	mapa['e'] = 'c';
	mapa[' '] = ' ';
	mapa['a'] = 'y';
	mapa['r'] = 'p';
	mapa['e'] = 'c';
	mapa[' '] = ' ';
	mapa['t'] = 'r';
	mapa['w'] = 't';
	mapa['e'] = 'c';
	mapa['n'] = 's';
	mapa['t'] = 'r';
	mapa['y'] = 'a';
	mapa[' '] = ' ';
	mapa['s'] = 'd';
	mapa['i'] = 'k';
	mapa['x'] = 'm';
	mapa[' '] = ' ';
	mapa['f'] = 'w';
	mapa['a'] = 'y';
	mapa['c'] = 'f';
	mapa['t'] = 'r';
	mapa['o'] = 'e';
	mapa['r'] = 'p';
	mapa['i'] = 'k';
	mapa['a'] = 'y';
	mapa['l'] = 'm';
	mapa[' '] = ' ';
	mapa['p'] = 'r';
	mapa['o'] = 'e';
	mapa['s'] = 'd';
	mapa['s'] = 'd';
	mapa['i'] = 'k';
	mapa['b'] = 'n';
	mapa['i'] = 'k';
	mapa['l'] = 'm';
	mapa['i'] = 'd';
	mapa['t'] = 'r';
	mapa['i'] = 'k';
	mapa['e'] = 'c';
	mapa['s'] = 'd';
	mapa['d'] = 's';
	mapa['e'] = 'o';
	mapa[' '] = ' ';
	mapa['k'] = 'i';
	mapa['r'] = 't';
	mapa[' '] = ' ';
	mapa['k'] = 'i';
	mapa['d'] = 's';
	mapa[' '] = ' ';
	mapa['e'] = 'o';
	mapa['o'] = 'k';
	mapa['y'] = 'a';
	mapa['a'] = 'y';
	mapa[' '] = ' ';
	mapa['k'] = 'i';
	mapa['w'] = 'f';
	mapa[' '] = ' ';
	mapa['a'] = 'y';
	mapa['e'] = 'o';
	mapa['j'] = 'u';
	mapa[' '] = ' ';
	mapa['t'] = 'w';
	mapa['y'] = 'a';
	mapa['s'] = 'n';
	mapa['r'] = 't';
	mapa[' '] = ' ';
	mapa['r'] = 't';
	mapa['e'] = 'o';
	mapa[' '] = ' ';
	mapa['u'] = 'j';
	mapa['j'] = 'u';
	mapa['d'] = 's';
	mapa['r'] = 't';
	mapa[' '] = ' ';
	mapa['l'] = 'g';
	mapa['k'] = 'i';
	mapa['g'] = 'v';
	mapa['c'] = 'e';
	mapa[' '] = ' ';
	mapa['j'] = 'u';
	mapa['v'] = 'p';
	mapa['z'] = 'q';
	mapa['q'] = 'z';
	mapa['m'] = 'l';
	mapa['i'] = 'd';
	mapa['b'] = 'h';
	mapa['h'] = 'x';
	mapa['f'] = 'c';
	mapa['n'] = 'b';

	int n;
	scanf("%d\n", &n);
	
	for (int i = 1; i <= n; i++) {
		gets(s);
		printf("Case #%d: ", i);
		for (int j = 0; j < strlen(s); j++) printf("%c", mapa[s[j]]);
		puts("");
	}
}
